baseURL = 'https://bostondh.github.io/'
languageCode = 'en-us'
title = 'Boston Digital Humanities'
theme = 'hugo-universal-theme'

[params]
	disabled_logo = true
	logo_text = "Boston DH"
	about_us = "Boston DH is an informal association of educational and cultural institutions in New England."
	contact_url = "/contact"
	address="""<p>
				  <a href="">Boston DH Listserv</a><br>
				  <a href="mailto:kaylen.dwyer@tufts.edu">Site Administrator</a>
				</p>"""


[params.see_more]
	enable = true
	title = "Boston Digital Humanities"
	subtitle = "The Boston Digital Humanities Consortium is an informal association of educational and cultural institutions in New England committed to the collaborative development of teaching, learning, and scholarship in the digital humanities and computational social sciences."
	link_url = "https://listserv.neu.edu/cgi-bin/wa?SUBED1=BOSTONDH"
	link_text = "Join the Mailing List"


# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1


[[menu.main]]
    name       = "Events"
    identifier = "menu.events"
    url        = ""
    weight     = 2

[[menu.main]]
    name       = "Past Events"
    identifier = "section.past-events"
    url        = ""
    weight     = 1
    parent     = "menu.events"
    post       = 3

 [[menu.main]]
    name       = "2019 Symposium"
    url        = "https://harvard-dssg.github.io/boston-area-dss/"
    weight     = 1
    parent     = "section.past-events"

  [[menu.main]]
    name       = "2023 Symposium"
    url        = "https://symposium2023.dhlab.mit.edu/"
    weight     = 2
    parent     = "section.past-events"



[[menu.main]]
    name       = "2024 Symposium"
    identifier = "section.current-events"
    url        = ""
    weight     = 2
    parent     = "menu.events"
    post       = 4

[[menu.main]]
    name       = "About"
    url        = "/symposium-2024"
    weight     = 1
    parent     = "section.current-events"

[[menu.main]]
    name       = "Call for Proposals"
    url        = "/symposium-2024-cfp"
    weight     = 2
    parent     = "section.current-events"



